import React, { useState } from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import PackageList from '../components/PackageList'
import Header from '../components/Header'
import Form from '../components/Form'

const Caixa: NextPage = () => {
    const [selected, setSelected] = useState(-1)

    return (
        <div>
            <Head>
                <title>Caixa</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <h1
                    style={{
                        textAlign: 'center',
                        fontSize: 56,
                        marginBottom: 30
                    }}
                >
                    Caixa
                </h1>
                <div style={{ float: 'left' }}>
                    <PackageList
                        selected={selected}
                        setSelected={setSelected}
                    />
                </div>

                <div style={{ float: 'right' }}>
                    <div id="form-container">
                        <Header
                            title="Digite o Código do Produto"
                            bgColor="#00B2FF"
                        />

                        <Form
                            placeholder="ex: 123456789"
                            buttonText="Pesquisar"
                        />

                        <h1
                            style={{
                                marginLeft: '2.5%',
                                marginTop: 30,
                                color: '#00B2FF'
                            }}
                        >
                            Quantidade
                        </h1>
                        <Form
                            placeholder="ex: 10"
                            buttonText="Vender"
                            disabled={selected === -1 ? true : false}
                        />
                    </div>

                    <div style={{ marginTop: 30 }}>
                        <form action="/" id="button-container">
                            <input
                                type="submit"
                                value="Trocar para Modo Estoque"
                                id="button-submit"
                            />
                        </form>
                    </div>
                </div>
            </main>
        </div>
    )
}

export default Caixa
