import type { NextPage } from 'next'
import Head from 'next/head'
import React, { useEffect, useState } from 'react'
import { useDispatch } from 'react-redux'
import Form from '../components/Form'
import Header from '../components/Header'
import PackageList from '../components/PackageList'
import { useReduxState } from '../hooks/useReduxState'
import { asyncGetPackages, asyncGetShelf, asyncPurchase } from '../store/Package.store'
import { Interaction } from '../types'

const Home: NextPage = () => {
    const [selected, setSelected] = useState('')
    const [searchCode, setSearchCode] = useState('')
    const [take, setTake] = useState('')
    const dispatch = useDispatch()
    const { packages } = useReduxState();

    useEffect(() => {
        dispatch(asyncGetPackages())
        dispatch(asyncGetShelf())
    }, [])

    const disableButton = () => {
        if (!selected) {
            return true
        }
        if (take === '') {
            return true
        }
        const foundShelf = packages.shelfValues.find(
            (item) => item.id === selected
        )

        if ((foundShelf?.amount ?? 0) - parseInt(take) < 0) {
            return true
        }

        return false
    }

    const onSubmit = () => {
        const foundShelf = packages.shelfValues.find(
            (item) => item.id === selected
        )
        const payload: Interaction = {
            id: selected,
            amount: parseInt(take),
            newShelfAmount: (foundShelf?.amount ?? 0) - parseInt(take),
            newStockAmount: 0
        }
        dispatch(asyncPurchase(payload))
    }

    return (
        <div>
            <Head>
                <title>Caixa</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="mx-28">
                <header className="mt-3 mb-7">
                    <h1 className="text-center text-5xl font-bold text-zinc-300">
                        Caixa
                    </h1>
                </header>

                <div className="flex">
                    <div className="mr-16">
                        <PackageList
                            data={packages.shelfValues}
                            selected={selected}
                            setSelected={setSelected}
                            searchCode={searchCode}
                        />
                    </div>

                    <div className="flex flex-col ml-48 items-center">
                        <div>
                            <div id="form-container">
                                <Header title="Digite o Lote do Produto" />

                                <Form
                                    placeholder="ex: 10"
                                    onChange={setSearchCode}
                                    take={searchCode}
                                />

                                <h1 className="text-3xl ml-3 mt-9 text-blue-500">
                                    Quantidade
                                </h1>
                                <Form
                                    disabledButton={disableButton()}
                                    placeholder="ex: 10"
                                    buttonText="Vender"
                                    button
                                    disabled={!selected}
                                    onChange={setTake}
                                    take={take}
                                    onSubmit={onSubmit}
                                />
                            </div>
                        </div>

                        <div className="mt-10">
                            <form action="/">
                                <input
                                    type="submit"
                                    value="Trocar para Modo Estoque"
                                    className="w-70 h-24 bg-blue-500 rounded-xl p-5 text-white text-xl font-bold hover:bg-blue-600 transition-colors"
                                />
                            </form>
                        </div>
                    </div>
                </div>
            </main>
        </div>
    )
}

export default Home
