import React, { useState } from 'react'
import type { NextPage } from 'next'
import PackageList from '../components/PackageList'
import Header from '../components/Header'
import Form from '../components/Form'
import Head from 'next/head'

const Home: NextPage = () => {
    const [selected, setSelected] = useState('')
    const [searchCode, setSearchCode] = useState('')
    const [take, setTake] = useState('')

    return (
        <div>
            <Head>
                <title>Estoque</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="mx-28">
                <header className="mt-3 mb-7">
                    <h1 className="text-center text-5xl font-bold text-zinc-300">
                        Estoque
                    </h1>
                </header>

                <div className="flex">
                    <div className="mr-16">
                        <PackageList
                            selected={selected}
                            setSelected={setSelected}
                            searchCode={searchCode}
                        />
                    </div>

                    <div className="flex flex-col ml-16 items-center">
                        <div>
                            <div id="form-container">
                                <Header title="Digite o Código do Produto" />

                                <Form
                                    placeholder="ex: 123456789"
                                    buttonText="Pesquisar"
                                    onChange={setSearchCode}
                                />

                                <h1 className="text-2xl ml-3 mt-9 text-blue-500">
                                    Quantidade
                                </h1>
                                <Form
                                    placeholder="ex: 10"
                                    buttonText="Retirar"
                                    button
                                    disabled={!selected}
                                    onChange={setTake}
                                    take={take}
                                />
                            </div>
                        </div>

                        <div className="mt-10">
                            <form action="/caixa">
                                <input
                                    type="submit"
                                    value="Trocar para Modo Caixa"
                                    className="w-70 h-24 bg-blue-500 rounded-xl p-5 text-white text-xl font-bold hover:bg-blue-600 transition-colors"
                                />
                            </form>
                        </div>
                    </div>
                </div>
            </main>
        </div>
    )
}

export default Home
