import React from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import PackageList from '../components/PackageList'
import Header from '../components/Header'

const Home: NextPage = () => {
    return (
        <div>
            <Head>
                <title>Estoque</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <div style={{ float: 'left' }}>
                    <PackageList />
                </div>

                <div style={{ float: 'right' }}>
                    <div id="form-container">
                        <Header
                            title="Digite o Código do Produto"
                            bgColor="#00B2FF"
                        />

                        <form action="" id="form-form">
                            <input
                                type="text"
                                id="form-input"
                                placeholder="ex: 123456789"
                            />
                            <input
                                type="submit"
                                value="Pesquisar"
                                id="form-submit"
                            />
                        </form>
                    </div>

                    <div style={{ marginTop: 125 }}>
                        <form action="" id="button-container">
                            <input
                                type="submit"
                                value="Trocar para Modo Caixa"
                                id="button-submit"
                            />
                        </form>
                    </div>
                </div>
            </main>
        </div>
    )
}

export default Home
